.TH sixarm-debian-postgresql-packages 1 "2011-03-12" "SixArm.com" "http://sixarm.com" 
.SH NAME 
sixarm-debian-postgresql-packages \- postgresql packages we like to use together

.SH SYNOPSIS
.B sixarm-debian-postgresql-packages

.SH DESCRIPTION
PostgreSQL packages we like to use together.

.SH BUGS
To report a bug, please send email to sixarm@sixarm.com

.SH AUTHORS
.TP
.B Joel Parker Henderson at SixArm.com
.I http://sixarm.com
